### PR TITLE
Refreshing with new meta-clanton

### PR DESCRIPTION
**Pull request by kmsywula**
Fixed grub problem and put brand new meta-clanton here. At this point no patches from patches/... are necessary.

### CODE REVIEW

**Comment by ndgbuilder** [comment]
Can you please also update the readme with the correct build steps?

**Comment by calvinatintel** [comment]
Crap, I forgot to log out from ndgbuilder. The previous message was from me.

**Comment by kmsywula** [comment]
What exactly do you mean? Build steps didn't change as that was a requirement - Manoel hardcoded them in the book. The only thing that changed is the version in file name. I'm not sure we should touch that. As for now README is the same as book and _it works_ assuming user is clever enough to extract file with bumped version number at the same time _not having the old one_.

**Comment by calvinatintel** [comment]
Readme.txt in this repo still references patches_v1.0.4.tar.gz and meta-clanton_v1.0.1. That needs to be updated.

**Comment by kmsywula** [comment]
Is that the proper way of adding new stuff to existing pull-request?

**Comment by calvinatintel** [comment]
You just did it. Do we still need to patch meta-clanton?

**Comment by kmsywula** [comment]
There are many answers. Grub is fixed for now in meta-clanton, dtc is fixed on poky. All of the patches that used to be in Jenkins/patches-xyz.tar.gz archive are integrated into meta-clanton layer and checked into Galileo-Runtime. As a matter of fact it's all subject of this code review.
I preserved the patch.meta-clanton.sh script though to keep consistent instructions. That script does not do any patching however anymore.
What we know for now is that OpenCV is broken and I tried to upstream a patch without a success. That's something we can fix locally in meta-clanton as well by either applying a patch directly and repacking the archive, or introducing that back into patch.meta-clanton.sh script.

**Comment by manoelramonintel** [comment]
let's keep in the patches.sh only temporarily ... I think we can patch meta-oe/meta-clanton without problems from there. Calvin, just to give you a background... grub is broken for both builds and opencv only for SD releases.

**Comment by calvinatintel** [comment]
Running a build to verify the process now...

**Comment by kmsywula** [comment]
"grub is broken for both builds and opencv only for SD releases"
grub _used to be broken_ and this pull-request fixes it. Please be precise :)
OpenCV as mentioned has invalid download URI and breaks the build.

**Comment by calvinatintel** [comment]
Pulling in per Manoel's approval

**Comment by calvinatintel** [comment]
Should I move the 1.0.4 tag too? Or do I tag the latest with 1.0.5?

**Comment by manoelramonintel** [comment]
keep 1.0.4

**Comment by manoelramonintel** [comment]
approved!

**Comment by calvinatintel** [comment]
1.0.4 tag moved to this commit

**Pull request merged**
